server:
  port: 8083

api:
  json-place-holder:
    domain: 'jsonplaceholder.typicode.com'
    endpoints:
      users: '/users'
      posts: '/posts'
      albums: '/albums'

database: 
  db-name: "db_2403"

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)